### ISSUE TITLE
relative_path_from: different prefix: (ArgumentError)

### ISSUE THREAD

**Issue by mmistakes** [algolia/jekyll-algolia#47]
### What is the current behavior?

Installed `jekyll-algolia`, added `algolia` configs to _config.yml and run `bundle exec jekyll algolia --dry-run --trace --verbose`

### What is your expected behavior?

Successfully complete a dry-run.

### Git repository to reproduce the issue:

I have a fairly complex [Jekyll repo](https://github.com/mmistakes/made-mistakes-jekyll) I'm testing this with (using Gulp, etc.). Not entirely sure if the problem is because I have `source` and `destination` set in _config.yml or if maybe it's related to a plugin (perhaps [jekyll-paginate-v2](https://github.com/sverrirs/jekyll-paginate-v2) since it seems to error out when ignoring files for the index)

Here's the full stacktrace:

```
Extracting records...
Skipping _pages/404.md
Extracting records from _pages/about.md
Skipping articles.xml
Skipping atom.xml
Extracting records from _pages/contact.md
Extracting records from _pages/faqs.md
Skipping feed.json
Extracting records from _pages/home.md
Skipping humans.txt
Skipping mastering-paper.xml
Skipping paperfaces.xml
Extracting records from _pages/portraits.md
Skipping procreate-paintings.xml
Skipping robots.txt
Extracting records from _pages/sitemap.md
Extracting records from _pages/style-guide.md
Extracting records from _pages/support.md
Extracting records from _pages/tag.md
Extracting records from _pages/terms.md
Skipping til.xml
Extracting records from _pages/work.md
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping .html
Skipping sitemap.xml
E:/Ruby24-x64/lib/ruby/2.4.0/pathname.rb:520:in `relative_path_from': different prefix: "E:/" and ".tmp/src" (ArgumentError)
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.1.2/lib/jekyll/algolia/file_browser.rb:52:in `relative_path'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.1.2/lib/jekyll-algolia.rb:94:in `block in write'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:329:in `block (2 levels) in each_site_file'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:328:in `each'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:328:in `block in each_site_file'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:327:in `each'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:327:in `each_site_file'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.1.2/lib/jekyll-algolia.rb:93:in `write'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:75:in `process'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.1.2/lib/jekyll-algolia.rb:57:in `run'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.1.2/lib/jekyll/commands/algolia.rb:42:in `block (2 levels) in init_with_program'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/exe/jekyll:15:in `<top (required)>'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/jekyll:23:in `load'
        from E:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/jekyll:23:in `<main>'
```

### Ruby version used:

ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

### Jekyll version used:

jekyll 3.7.2

**Comment by pixelastic** [comment]
Thanks for the report. I'm going to have a look at the repository you linked.

**Comment by mmistakes** [comment]
I pushed up a [simple test repo](https://github.com/mmistakes/jekyll-algolia-source-folder) that demonstrates the issue if that helps.

Seems like if you define `source` in Jekyll's _config.yml it breaks the Algolia plugin.

**Comment by nakoo** [comment]
I also have trouble with it.

**Comment by pixelastic** [comment]
@mmistakes @nakoo I just released v1.1.3 that should fix the issue with the source. Could you let me know if it works for you?

_I'll close the issue for now, but will re-open if you tell me it's still broken_

**Comment by mmistakes** [comment]
This fixes the issue for me @pixelastic, thanks!

**Comment by claudiuconstantin** [comment]
I'm currently encountering this issue on Windows:

```
Extracting records...
jekyll 3.8.6 | Error:  different prefix: "C:/" and "D:/path-to-jekyll"
```
