### ISSUE TITLE
Indexing error - NoMethodError: undefined method `to_time'

### ISSUE THREAD

**Issue by cinhtau** [algolia/jekyll-algolia#70]
## I want to report a bug:

Upgraded Jekyll and all other plugins. In the process also upgrade jekyll-algolia. Algolia was working fine before with the given content. No content changes werde made.

Indexing command `bundle exec jekyll algolia` fails now.

### Ruby version used:
- ruby v2.4.1
- jekyll-algolia 1.4.0

### Jekyll version used:
- jekyll 3.8.1

See below the trace

```bash
tan@omega:~/docs$ bundle exec jekyll algolia -t --verbose
...
Extracting records from collections/_pages/hpns/001-nonstop-os.md                
bundler: failed to load command: jekyll (/home/tan/.rbenv/versions/2.4.1/bin/jekyll)
NoMethodError: undefined method `to_time' for "10.07.2017 15:00":String
Did you mean?  to_i
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.4.0/lib/jekyll/algolia/file_browser.rb:245:in `date'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.4.0/lib/jekyll/algolia/file_browser.rb:145:in `metadata'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.4.0/lib/jekyll/algolia/extractor.rb:18:in `run'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.4.0/lib/jekyll/algolia/overwrites/jekyll-algolia-site.rb:122:in `block in push'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.8.1/lib/jekyll/site.rb:332:in `block (2 levels) in each_site_file'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.8.1/lib/jekyll/site.rb:331:in `each'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.8.1/lib/jekyll/site.rb:331:in `block in each_site_file'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.8.1/lib/jekyll/site.rb:330:in `each'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.8.1/lib/jekyll/site.rb:330:in `each_site_file'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.4.0/lib/jekyll/algolia/overwrites/jekyll-algolia-site.rb:112:in `push'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.4.0/lib/jekyll/algolia/overwrites/jekyll-algolia-site.rb:37:in `process'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.4.0/lib/jekyll-algolia.rb:74:in `run'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-algolia-1.4.0/lib/jekyll/commands/algolia.rb:31:in `block (2 levels) in init_with_program'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /home/tan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.8.1/exe/jekyll:15:in `<top (required)>'
  /home/tan/.rbenv/versions/2.4.1/bin/jekyll:22:in `load'
  /home/tan/.rbenv/versions/2.4.1/bin/jekyll:22:in `<top (required)>'
```

The mentioned file has this yaml frontmatter:

```yaml
layout: page
title: "OS"
permalink: /pages/hpns/os
date: '10.07.2017 15:00'
category: HP-NonStop
```

**Comment by cinhtau** [comment]
If I lock the version to 1.1.5 it works again. HTH

**Comment by pixelastic** [comment]
Hello and thanks a lot for the detailed bug report!

I think what is happening is that the plugin tries to parse the date of the page and convert it to a timestamp. By default it resolves to the date as exposed by Jekyll (as a Date object), but in your case you had it overwritten in your front matter and the conversion fails.

A quick workaround would be for you to rename your `date` entry in the frontmatter to something else (if doable).

What I could do in the plugin would be to check if the date field is a string and then try to parse it.

**Comment by cinhtau** [comment]
@pixelastic Thanks for the elaborate explanation! I was not aware that date in yaml is specified differently. 

I changed this

```
date: '10.07.2017 15:00'
```

into this 

```
date: 10.07.2017 15:00
```

and it works! No need to change anything. It might help others if this in the README.md :smile:

**Comment by pixelastic** [comment]
Glad you could find a solution :)

I think it has more to do with Jekyll as a whole than with the plugin specifically so I won't be adding it to the Readme for now. If I see more people struggling with that in the issues, then I'll add it :)

Thanks!
